import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { ChevronRight, Activity, CalendarDays, ShieldAlert, Cpu, CheckCircle2, RotateCcw, Loader2 } from 'lucide-react';
import { submitOnboardingToAI } from './services/api';
import type { OnboardingData, AIPlanResponse } from './services/api';
import type { Result } from './utils/errors';
import { BackgroundPaths } from '@/components/ui/background-paths';
import { RadarEffectDemo } from '@/components/radar-demo';

export default function App() {
  const [hasStarted, setHasStarted] = useState(false);
  const [step, setStep] = useState(0);
  const [formData, setFormData] = useState<OnboardingData>({
    statsAndGoals: '',
    schedule: '',
    limitations: '',
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submissionResult, setSubmissionResult] = useState<Result<AIPlanResponse> | null>(null);

  const questions = [
    {
      id: 'statsAndGoals',
      icon: <Activity className="w-8 h-8 text-red-500 mb-4" />,
      title: "What are your current lifting stats and strength goals?",
      placeholder: "e.g., I currently squat 100kg but want to reach 140kg by the end of the year. My main goal is raw powerlifting strength...",
    },
    {
      id: 'schedule',
      icon: <CalendarDays className="w-8 h-8 text-red-500 mb-4" />,
      title: "How many days per week can you train, and for how long?",
      placeholder: "e.g., I can train 4 days a week, mostly in the evenings for about 60-90 minutes...",
    },
    {
      id: 'limitations',
      icon: <ShieldAlert className="w-8 h-8 text-red-500 mb-4" />,
      title: "Do you have any injuries or movement limitations?",
      placeholder: "e.g., I have a slight shoulder impingement on my left side, avoiding overhead barbell presses...",
    }
  ];

  const handleNext = () => {
    if (step < questions.length - 1) {
      setStep(step + 1);
    } else {
      handleSubmit();
    }
  };

  const handleBack = () => {
    if (step > 0) {
      setStep(step - 1);
      setSubmissionResult(null);
    }
  };

  const handleReset = () => {
    setHasStarted(false);
    setStep(0);
    setSubmissionResult(null);
    setFormData({ statsAndGoals: '', schedule: '', limitations: '' });
  };

  const handleSubmit = async () => {
    setIsSubmitting(true);
    setSubmissionResult(null);
    const result = await submitOnboardingToAI(formData);
    setIsSubmitting(false);
    setSubmissionResult(result);
  };

  if (!hasStarted) {
    return (
      <div className="w-full flex flex-col relative z-10">
        <BackgroundPaths onStart={() => setHasStarted(true)} />
        <RadarEffectDemo />
      </div>
    );
  }

  // ─── Loading State ───
  if (isSubmitting) {
    return (
      <div className="min-h-screen bg-background text-foreground font-sans flex flex-col">
        <main className="flex-1 flex items-center justify-center px-6">
          <div className="flex flex-col items-center gap-6 text-center">
            <div className="relative">
              <div className="w-20 h-20 rounded-full bg-red-950/50 flex items-center justify-center border border-red-900/30">
                <Loader2 className="w-10 h-10 text-red-500 animate-spin" />
              </div>
            </div>
            <div>
              <h2 className="text-2xl font-bold tracking-tight mb-2 text-white">Your Plan Is Being Forged</h2>
              <p className="text-red-300/60 max-w-md">Claude is analyzing your profile and building a science-backed training program. This typically takes 10-20 seconds.</p>
            </div>
            <div className="flex gap-1.5 mt-4">
              <div className="w-2 h-2 rounded-full bg-red-500 animate-bounce" style={{ animationDelay: '0ms' }} />
              <div className="w-2 h-2 rounded-full bg-red-500 animate-bounce" style={{ animationDelay: '150ms' }} />
              <div className="w-2 h-2 rounded-full bg-red-500 animate-bounce" style={{ animationDelay: '300ms' }} />
            </div>
          </div>
        </main>
      </div>
    );
  }

  // ─── Result: Success ───
  if (submissionResult?.ok) {
    return (
      <div className="min-h-screen bg-background text-foreground font-sans">
        <main className="max-w-4xl mx-auto px-6 pt-12 pb-24">
          <div className="flex items-center gap-3 mb-8 pb-6 border-b border-red-900/30">
            <div className="w-12 h-12 bg-green-900/30 text-green-500 rounded-full flex items-center justify-center border border-green-800/30">
              <CheckCircle2 className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-2xl font-bold tracking-tight text-white">Your Personalized Plan</h2>
              <p className="text-red-300/50 text-sm">Generated by Claude based on your profile</p>
            </div>
          </div>

          {/* Rendered Markdown Plan */}
          <article className="prose prose-invert prose-headings:text-white prose-headings:font-bold prose-headings:tracking-tight prose-h2:text-xl prose-h2:mt-10 prose-h2:mb-4 prose-h3:text-lg prose-h3:mt-6 prose-h3:mb-3 prose-p:text-red-100/80 prose-p:leading-relaxed prose-li:text-red-100/80 prose-li:leading-relaxed prose-em:text-red-400/70 prose-strong:text-white prose-table:text-sm prose-th:bg-red-950/40 prose-th:text-red-200 prose-th:p-3 prose-td:p-3 prose-td:text-red-100/70 prose-td:border-red-900/30 prose-th:border-red-900/30 prose-hr:border-red-900/30 max-w-none">
            <ReactMarkdown>{submissionResult.value.plan}</ReactMarkdown>
          </article>

          {/* Footer Action */}
          <div className="mt-16 pt-8 border-t border-red-900/30 flex justify-center">
            <button
              onClick={handleReset}
              className="bg-red-600 text-white hover:bg-red-700 transition-colors px-8 py-3 rounded-md font-medium inline-flex items-center gap-2 group shadow-lg shadow-red-900/30"
            >
              Start Over <RotateCcw className="w-4 h-4 group-hover:-rotate-90 transition-transform duration-300" />
            </button>
          </div>
        </main>
      </div>
    );
  }

  // ─── Result: Error ───
  if (submissionResult && !submissionResult.ok) {
    return (
      <div className="min-h-screen bg-background text-foreground font-sans flex flex-col">
        <main className="flex-1 flex items-center justify-center px-6">
          <div className="flex flex-col items-center justify-center text-center max-w-lg">
            <div className="w-16 h-16 bg-red-950/50 text-red-500 rounded-full flex items-center justify-center mb-6 border border-red-900/30">
              <Cpu className="w-8 h-8" />
            </div>
            <h2 className="text-3xl font-bold mb-4 tracking-tight text-white">AI Engine Unreachable</h2>
            <p className="text-red-300/60 mb-4 text-lg">
              We couldn't connect to the AI brain right now. Our circuit breaker prevented cascading failures.
            </p>
            <div className="bg-red-950/40 border border-red-900/40 text-red-300 rounded-lg p-4 w-full mb-8 text-sm text-left">
              <strong className="text-red-400">Error Details:</strong> {submissionResult.error.message}
            </div>
            <div className="flex gap-4">
              <button
                onClick={() => { setSubmissionResult(null); setStep(2); }}
                className="bg-surface border border-red-900/40 text-red-200 hover:bg-surface-hover transition-colors px-6 py-3 rounded-md font-medium"
              >
                Go Back
              </button>
              <button
                onClick={handleSubmit}
                className="bg-red-600 text-white hover:bg-red-700 transition-colors px-6 py-3 rounded-md font-medium shadow-lg shadow-red-900/30"
              >
                Retry
              </button>
            </div>
          </div>
        </main>
      </div>
    );
  }

  // ─── Onboarding Questions ───
  const currentQuestion = questions[step];

  return (
    <div className="min-h-screen bg-background text-foreground font-sans selection:bg-red-900/40">
      <main className="max-w-5xl mx-auto px-6 pt-16 pb-24">
        <div className="w-full max-w-2xl mx-auto space-y-8" key={step}>

          {/* Progress */}
          <div className="w-full mb-10 mt-8">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-medium text-red-300/50 tracking-wide uppercase">Question {step + 1} of {questions.length}</span>
              <span className="text-sm font-medium text-red-400">{Math.round((step / questions.length) * 100)}%</span>
            </div>
            <div className="h-2 bg-red-950/40 rounded-full overflow-hidden">
              <div
                className="h-full bg-red-600 transition-all duration-500 ease-out"
                style={{ width: `${(step / questions.length) * 100}%` }}
              />
            </div>
          </div>

          {/* Question Card */}
          <div className="bg-card border border-card-border shadow-xl shadow-red-950/20 rounded-xl p-8 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-red-600" />
            {currentQuestion.icon}
            <h2 className="text-2xl font-bold tracking-tight text-white mb-6">
              {currentQuestion.title}
            </h2>
            <textarea
              className="w-full min-h-[160px] p-4 bg-input-bg border border-red-900/30 rounded-lg focus:ring-2 focus:ring-red-600 focus:border-transparent outline-none transition-all resize-none text-red-100 placeholder:text-red-300/30"
              placeholder={currentQuestion.placeholder}
              value={formData[currentQuestion.id as keyof OnboardingData]}
              onChange={(e) => setFormData({ ...formData, [currentQuestion.id]: e.target.value })}
              autoFocus
            />
          </div>

          {/* Buttons */}
          <div className="flex items-center justify-between pt-6">
            <button
              onClick={handleBack}
              className={`px-6 py-3 font-medium text-red-300/60 hover:text-red-200 transition-colors ${step === 0 ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}
            >
              ← Back
            </button>

            <button
              onClick={handleNext}
              disabled={!formData[currentQuestion.id as keyof OnboardingData].trim()}
              className="group bg-red-600 text-white hover:bg-red-700 disabled:opacity-40 disabled:cursor-not-allowed transition-all px-8 py-3 rounded-md font-medium inline-flex items-center gap-2 shadow-lg shadow-red-900/30"
            >
              {step === questions.length - 1 ? (
                'Generate Plan'
              ) : (
                <span className="flex items-center gap-2">
                  Continue <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </span>
              )}
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
