import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { ChevronRight, Dumbbell, Activity, CalendarDays, ShieldAlert, Cpu, CheckCircle2, RotateCcw, Loader2 } from 'lucide-react';
import { submitOnboardingToAI } from './services/api';
import type { OnboardingData, AIPlanResponse } from './services/api';
import type { Result } from './utils/errors';

export default function App() {
  const [step, setStep] = useState(0);
  const [formData, setFormData] = useState<OnboardingData>({
    statsAndGoals: '',
    schedule: '',
    limitations: '',
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submissionResult, setSubmissionResult] = useState<Result<AIPlanResponse> | null>(null);

  const questions = [
    {
      id: 'statsAndGoals',
      icon: <Activity className="w-8 h-8 text-black mb-4" />,
      title: "What are your current lifting stats and strength goals?",
      placeholder: "e.g., I currently squat 100kg but want to reach 140kg by the end of the year. My main goal is raw powerlifting strength...",
    },
    {
      id: 'schedule',
      icon: <CalendarDays className="w-8 h-8 text-black mb-4" />,
      title: "How many days per week can you train, and for how long?",
      placeholder: "e.g., I can train 4 days a week, mostly in the evenings for about 60-90 minutes...",
    },
    {
      id: 'limitations',
      icon: <ShieldAlert className="w-8 h-8 text-black mb-4" />,
      title: "Do you have any injuries or movement limitations?",
      placeholder: "e.g., I have a slight shoulder impingement on my left side, avoiding overhead barbell presses...",
    }
  ];

  const handleNext = () => {
    if (step < questions.length - 1) {
      setStep(step + 1);
    } else {
      handleSubmit();
    }
  };

  const handleBack = () => {
    if (step > 0) {
      setStep(step - 1);
      setSubmissionResult(null);
    }
  };

  const handleReset = () => {
    setStep(0);
    setSubmissionResult(null);
    setFormData({ statsAndGoals: '', schedule: '', limitations: '' });
  };

  const handleSubmit = async () => {
    setIsSubmitting(true);
    setSubmissionResult(null);

    const result = await submitOnboardingToAI(formData);

    setIsSubmitting(false);
    setSubmissionResult(result);
  };

  // ─── Loading State ───
  if (isSubmitting) {
    return (
      <div className="min-h-screen bg-white text-zinc-900 font-sans flex flex-col">
        <Header />
        <main className="flex-1 flex items-center justify-center px-6">
          <div className="flex flex-col items-center gap-6 text-center">
            <div className="relative">
              <div className="w-20 h-20 rounded-full bg-zinc-100 flex items-center justify-center">
                <Loader2 className="w-10 h-10 text-black animate-spin" />
              </div>
            </div>
            <div>
              <h2 className="text-2xl font-bold tracking-tight mb-2">Your Plan Is Being Forged</h2>
              <p className="text-zinc-500 max-w-md">Claude is analyzing your profile and building a science-backed training program. This typically takes 10-20 seconds.</p>
            </div>
            <div className="flex gap-1.5 mt-4">
              <div className="w-2 h-2 rounded-full bg-black animate-bounce" style={{ animationDelay: '0ms' }} />
              <div className="w-2 h-2 rounded-full bg-black animate-bounce" style={{ animationDelay: '150ms' }} />
              <div className="w-2 h-2 rounded-full bg-black animate-bounce" style={{ animationDelay: '300ms' }} />
            </div>
          </div>
        </main>
      </div>
    );
  }

  // ─── Result: Success ───
  if (submissionResult?.ok) {
    return (
      <div className="min-h-screen bg-white text-zinc-900 font-sans">
        <Header />
        <main className="max-w-4xl mx-auto px-6 pt-12 pb-24">
          <div className="flex items-center gap-3 mb-8 pb-6 border-b border-zinc-100">
            <div className="w-12 h-12 bg-green-100 text-green-600 rounded-full flex items-center justify-center">
              <CheckCircle2 className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-2xl font-bold tracking-tight">Your Personalized Plan</h2>
              <p className="text-zinc-500 text-sm">Generated by Claude based on your profile</p>
            </div>
          </div>

          {/* Rendered Markdown Plan */}
          <article className="prose prose-zinc prose-headings:font-bold prose-headings:tracking-tight prose-h2:text-xl prose-h2:mt-10 prose-h2:mb-4 prose-h3:text-lg prose-h3:mt-6 prose-h3:mb-3 prose-p:leading-relaxed prose-li:leading-relaxed prose-em:text-zinc-500 prose-table:text-sm prose-th:bg-zinc-50 prose-th:p-3 prose-td:p-3 prose-td:border-zinc-200 prose-th:border-zinc-200 max-w-none">
            <ReactMarkdown>{submissionResult.value.plan}</ReactMarkdown>
          </article>

          {/* Footer Action */}
          <div className="mt-16 pt-8 border-t border-zinc-100 flex justify-center">
            <button
              onClick={handleReset}
              className="bg-black text-white hover:bg-zinc-800 transition-colors px-8 py-3 rounded-md font-medium inline-flex items-center gap-2 group"
            >
              Generate New Plan <RotateCcw className="w-4 h-4 group-hover:-rotate-90 transition-transform duration-300" />
            </button>
          </div>
        </main>
      </div>
    );
  }

  // ─── Result: Error ───
  if (submissionResult && !submissionResult.ok) {
    return (
      <div className="min-h-screen bg-white text-zinc-900 font-sans flex flex-col">
        <Header />
        <main className="flex-1 flex items-center justify-center px-6">
          <div className="flex flex-col items-center justify-center text-center max-w-lg">
            <div className="w-16 h-16 bg-red-100 text-red-600 rounded-full flex items-center justify-center mb-6">
              <Cpu className="w-8 h-8" />
            </div>
            <h2 className="text-3xl font-bold mb-4 tracking-tight">AI Engine Unreachable</h2>
            <p className="text-zinc-500 mb-4 text-lg">
              We couldn't connect to the AI brain right now. Our circuit breaker prevented cascading failures.
            </p>
            <div className="bg-red-50 border border-red-100 text-red-800 rounded-lg p-4 w-full mb-8 text-sm text-left">
              <strong>Error Details:</strong> {submissionResult.error.message}
            </div>
            <div className="flex gap-4">
              <button
                onClick={() => { setSubmissionResult(null); setStep(2); }}
                className="bg-white border border-zinc-200 text-black hover:bg-zinc-50 transition-colors px-6 py-3 rounded-md font-medium"
              >
                Go Back
              </button>
              <button
                onClick={handleSubmit}
                className="bg-black text-white hover:bg-zinc-800 transition-colors px-6 py-3 rounded-md font-medium"
              >
                Retry
              </button>
            </div>
          </div>
        </main>
      </div>
    );
  }

  // ─── Onboarding Questions ───
  const currentQuestion = questions[step];

  return (
    <div className="min-h-screen bg-white text-zinc-900 font-sans selection:bg-zinc-200">
      <Header />
      <main className="max-w-5xl mx-auto px-6 pt-16 pb-24">
        <div className="w-full max-w-2xl mx-auto space-y-8" key={step}>

          {/* Progress */}
          <div className="w-full mb-10">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-medium text-zinc-500 tracking-wide uppercase">Question {step + 1} of {questions.length}</span>
              <span className="text-sm font-medium text-black">{Math.round((step / questions.length) * 100)}%</span>
            </div>
            <div className="h-2 bg-zinc-100 rounded-full overflow-hidden">
              <div
                className="h-full bg-black transition-all duration-500 ease-out"
                style={{ width: `${(step / questions.length) * 100}%` }}
              />
            </div>
          </div>

          {/* Question Card */}
          <div className="bg-white border border-zinc-100 shadow-sm rounded-xl p-8 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-black" />
            {currentQuestion.icon}
            <h2 className="text-2xl font-bold tracking-tight text-black mb-6">
              {currentQuestion.title}
            </h2>
            <textarea
              className="w-full min-h-[160px] p-4 bg-zinc-50 border border-zinc-200 rounded-lg focus:ring-2 focus:ring-black focus:border-transparent outline-none transition-all resize-none text-black placeholder:text-zinc-400"
              placeholder={currentQuestion.placeholder}
              value={formData[currentQuestion.id as keyof OnboardingData]}
              onChange={(e) => setFormData({ ...formData, [currentQuestion.id]: e.target.value })}
              autoFocus
            />
          </div>

          {/* Buttons */}
          <div className="flex items-center justify-between pt-6">
            <button
              onClick={handleBack}
              className={`px-6 py-3 font-medium text-zinc-600 hover:text-black transition-colors ${step === 0 ? 'opacity-0 pointer-events-none' : 'opacity-100'}`}
            >
              ← Back
            </button>

            <button
              onClick={handleNext}
              disabled={!formData[currentQuestion.id as keyof OnboardingData].trim()}
              className="group bg-black text-white hover:bg-zinc-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all px-8 py-3 rounded-md font-medium inline-flex items-center gap-2 shadow-sm"
            >
              {step === questions.length - 1 ? (
                'Generate Plan'
              ) : (
                <span className="flex items-center gap-2">
                  Continue <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </span>
              )}
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}

function Header() {
  return (
    <header className="border-b border-zinc-100 bg-white/80 backdrop-blur-md sticky top-0 z-10 w-full">
      <div className="max-w-5xl mx-auto px-6 h-20 flex items-center">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-black rounded-lg flex items-center justify-center shadow-sm">
            <Dumbbell className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="font-bold text-xl tracking-tight leading-none text-black">Aura<span className="text-zinc-400">Strength</span></h1>
            <p className="text-[10px] uppercase font-bold tracking-widest text-zinc-500 mt-1">AI Powered Science</p>
          </div>
        </div>
      </div>
    </header>
  );
}
